export interface GeneralDiffFile {
  path: string;
  oldPath?: string;
  status: 'modified' | 'added' | 'deleted' | 'renamed';
  additions: number;
  deletions: number;
  chunks: DiffChunk[];
}

export interface FileDiff {
  path: string;
  status: 'A' | 'M' | 'D';
  diff: string;
  additions: number;
  deletions: number;
}

export interface DiffChunk {
  header: string;
  oldStart: number;
  oldLines: number;
  newStart: number;
  newLines: number;
  lines: DiffLine[];
}

export interface DiffLine {
  type: 'add' | 'delete' | 'normal' | 'hunk' | 'remove' | 'context' | 'header';
  content: string;
  oldLineNumber?: number;
  newLineNumber?: number;
}

export interface ParsedDiff {
  chunks: DiffChunk[];
}

export interface DiffResponse {
  commit: string;
  files: DiffFile[];
  ignoreWhitespace?: boolean;
  isEmpty?: boolean;
  mode?: string;
  baseCommitish?: string;
  targetCommitish?: string;
}

export type LineNumber = number | [number, number];

export interface Comment {
  id: string;
  file: string;
  line: LineNumber;
  body: string;
  timestamp: string;
  codeContent?: string; // The actual code content for this line
}

// Jupyter Notebook specific types
/**
 * Represents a single cell in a Jupyter notebook
 */
export interface NotebookCell {
  /** Type of the cell: code, markdown, or raw */
  cell_type: 'code' | 'markdown' | 'raw';
  /** Source code/content of the cell, can be string or array of strings */
  source: string[] | string;
  /** Optional metadata associated with the cell */
  metadata?: Record<string, unknown>;
  /** Execution count for code cells (null if not executed) */
  execution_count?: number | null;
  /** Outputs generated by code cell execution */
  outputs?: NotebookOutput[];
}

/**
 * Represents output from a notebook cell execution
 */
export interface NotebookOutput {
  /** Type of output produced */
  output_type: 'stream' | 'display_data' | 'execute_result' | 'error';
  /** Data content of the output (for display_data, execute_result) */
  data?: Record<string, unknown>;
  /** Text content (for stream output) */
  text?: string[] | string;
  /** Stream name (stdout, stderr) for stream output */
  name?: string;
  /** Error name for error output */
  ename?: string;
  /** Error value for error output */
  evalue?: string;
  /** Error traceback for error output */
  traceback?: string[] | string;
}

/**
 * Represents the difference between two notebook cells
 */
export interface CellDiff {
  /** Index of the cell in the new notebook */
  cellIndex: number;
  /** Index of the cell in the old notebook (if different from cellIndex) */
  oldCellIndex?: number;
  /** Status of the cell change */
  status: 'added' | 'deleted' | 'modified' | 'moved' | 'unchanged';
  /** The cell in the old version */
  oldCell?: NotebookCell;
  /** The cell in the new version */
  newCell?: NotebookCell;
  /** Diff chunks for source code changes */
  sourceChanges?: DiffChunk[];
  /** Summary of output changes */
  outputChanges?: {
    added: NotebookOutput[];
    deleted: NotebookOutput[];
    modified: Array<{
      old: NotebookOutput;
      new: NotebookOutput;
    }>;
  };
  /** Diff chunks for output changes */
  outputDiffChunks?: DiffChunk[];
  /** Whether cell metadata has changed */
  metadataChanged?: boolean;
  /** Whether execution count has changed */
  executionCountChanged?: boolean;
}

/**
 * Represents a diff for an entire Jupyter notebook file
 */
export interface NotebookDiffFile {
  /** Path to the notebook file */
  path: string;
  /** Original path if file was renamed */
  oldPath?: string;
  /** Overall file status */
  status: 'modified' | 'added' | 'deleted' | 'renamed';
  /** Array of cell-level diffs */
  cellDiffs: CellDiff[];
  /** Whether notebook-level metadata has changed */
  metadataChanged?: boolean;
  /** Total number of cells added */
  totalCellsAdded: number;
  /** Total number of cells deleted */
  totalCellsDeleted: number;
  /** Total number of cells modified */
  totalCellsModified: number;
}

export interface NotebookDiff {
  files: NotebookDiffFile[];
}

export interface LineSelection {
  side: 'old' | 'new';
  lineNumber: number;
}

// Union type for all diff file types
export type DiffFile = GeneralDiffFile | NotebookDiffFile;
